-- Agent campaign workflow tables

-- Campaigns: top-level container for an agent-driven outreach run
create table if not exists agent_campaigns (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  conversation_id uuid references agent_conversations(id) on delete set null,
  title text not null default 'Untitled Campaign',
  status text not null default 'planning'
    check (status in ('planning', 'researching', 'enriching', 'drafting', 'review', 'approved', 'executing', 'completed', 'failed')),
  -- LLM plan output (Step 1)
  plan jsonb,
  -- User's original command
  user_prompt text,
  -- Warnings / risk flags
  warnings jsonb default '[]'::jsonb,
  -- Follow-up schedule structure
  followup_schedule jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Prospects discovered/enriched by the agent
create table if not exists agent_prospects (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references agent_campaigns(id) on delete cascade,
  -- Link to existing customer if matched
  customer_id uuid references customers(id) on delete set null,
  -- Raw prospect data
  name text,
  email text,
  company text,
  title text,
  linkedin_url text,
  source text, -- e.g. 'serp', 'manual', 'existing_customer'
  raw_data jsonb default '{}'::jsonb,
  -- Enrichment output (Step 3)
  enrichment jsonb, -- { tone, personal_hook, key_fact, confidence_score }
  confidence_score numeric(3,2),
  -- Flags
  risk_flags text[] default '{}',
  status text not null default 'discovered'
    check (status in ('discovered', 'enriched', 'drafted', 'approved', 'sent', 'skipped')),
  created_at timestamptz not null default now()
);

-- Email drafts generated by the agent
create table if not exists agent_email_drafts (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references agent_campaigns(id) on delete cascade,
  prospect_id uuid not null references agent_prospects(id) on delete cascade,
  step_number int not null default 1, -- 1 = initial, 2+ = follow-ups
  subject text not null,
  body text not null,
  -- Which template was used as base
  base_template_id uuid references email_templates(id) on delete set null,
  -- User can edit before approving
  user_edited boolean not null default false,
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'sent', 'failed')),
  created_at timestamptz not null default now()
);

-- Activity log for the agent's step-by-step progress
create table if not exists agent_activity_log (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references agent_campaigns(id) on delete cascade,
  step text not null, -- 'planning', 'researching', 'enriching', 'drafting', 'review', 'executing'
  message text not null,
  detail jsonb,
  created_at timestamptz not null default now()
);

-- Indexes
create index if not exists idx_agent_campaigns_org on agent_campaigns(organization_id);
create index if not exists idx_agent_prospects_campaign on agent_prospects(campaign_id);
create index if not exists idx_agent_email_drafts_campaign on agent_email_drafts(campaign_id);
create index if not exists idx_agent_activity_log_campaign on agent_activity_log(campaign_id);

-- RLS
alter table agent_campaigns enable row level security;
alter table agent_prospects enable row level security;
alter table agent_email_drafts enable row level security;
alter table agent_activity_log enable row level security;

create policy "Users can manage their org campaigns"
  on agent_campaigns for all
  using (organization_id in (
    select organization_id from organization_members where user_id = auth.uid()
  ));

create policy "Users can manage prospects in their org campaigns"
  on agent_prospects for all
  using (campaign_id in (
    select id from agent_campaigns where organization_id in (
      select organization_id from organization_members where user_id = auth.uid()
    )
  ));

create policy "Users can manage drafts in their org campaigns"
  on agent_email_drafts for all
  using (campaign_id in (
    select id from agent_campaigns where organization_id in (
      select organization_id from organization_members where user_id = auth.uid()
    )
  ));

create policy "Users can view activity log for their org campaigns"
  on agent_activity_log for all
  using (campaign_id in (
    select id from agent_campaigns where organization_id in (
      select organization_id from organization_members where user_id = auth.uid()
    )
  ));
